version: '3'
volumes:
  PhoneBookDbData:
services:
  database:
    image: "postgres:10-alpine"
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: amir_cwdb
      POSTGRES_PASSWORD: amirpostgres
      PGPASSWORD: amirpostgres
      POSTGRES_DB: cw_DB
      PGDATA: /db_data
    volumes:
    - PhoneBookDbData:/db_data
  cache:
    image: "memcached:alpine"
    ports:
      - 11211:11211